### ISSUE TITLE
Amazon Pay Orders Marked as Canceled Despite Successful Customer Charge

### ISSUE THREAD

**Issue by ijozwiak** [amzn/amazon-payments-magento-2-plugin#1280]
Orders that successfully switch to processing after payment capture are later being canceled due to duplicate session completion attempts in the Amazon Pay module.

### Affected Component:
`\Amazon\Pay\Model\CheckoutSessionManagement`

**Magento Version:** Adobe Commerce Ver.-2.4.7-p6
**Amazon Pay Extension Version:**

```
"name": "amzn/amazon-pay-magento-2-module",
"version": "5.18.2",
```

### Steps to Reproduce

1. Place an order using Amazon Pay.
2. Allow the order to be processed normally – capture succeeds, and status changes to processing.
3. A duplicate request is sent to `checkout/completeSession` for the same `amazonCheckoutSessionId`.
4. The session is attempted to be completed again.

### Actual Result

- Order is switched to processing.
- A second request to `completeSession` triggers `Something went wrong. Choose another payment method for checkout and try again.`
- Order status changes to canceled, even though payment was successfully captured.

**Order history example:**

<img width="1354" height="629" alt="Image" src="https://github.com/user-attachments/assets/006b89e2-7595-49a6-a1de-64ea9ae6c3d5" />

### Expected Result

- Once the session is completed and the order is in processing, further duplicate attempts to complete the session should be ignored.
- No cancellation should occur after successful capture.

### Technical Analysis

The message originates from: `vendor/amzn/amazon-pay-magento-2-module/Model/CheckoutSessionManagement.php:711`

**Triggered by:**

- `vendor/amzn/amazon-pay-magento-2-module/Model/CheckoutSessionManagement.php:789`
- `vendor/amzn/amazon-pay-magento-2-module/Model/CheckoutSessionManagement.php:1206`
- `vendor/amzn/amazon-pay-magento-2-module/Model/CheckoutSessionManagement.php:1328`

**Executed by:**

- `\Amazon\Pay\Model\Resolver\CompleteCheckoutSession::resolve`
- `\Amazon\Pay\Controller\Checkout\CompleteSession::execute` - confirmed for us
- `\Amazon\Pay\Cron\CleanUpIncompleteSessions::processTransaction`

Logs confirm multiple simultaneous requests to `checkout/completeSession` for the same session ID.

### Suggested Fix
Add a condition in: `\Amazon\Pay\Model\CheckoutSessionManagement::completeAmazonCheckoutSession`
Skip processing if the related order already has status processing. 

Example code:
```
if ($order->getState() === Order::STATE_PROCESSING) {
    return; // Do not attempt to complete again
}
```

### Logs

Use this oneliner directly in the /var/log/nginx directory

```
(for f in *; do case "$f" in *.zst|*.zstd) zstd -dc "$f";; *) cat "$f";; esac; done) \
| grep -oP 'checkout/completeSession/\?amazonCheckoutSessionId=[^" ]+' \
| sort \
| uniq -c \
| awk '$1>1'
```

<img width="506" height="526" alt="Image" src="https://github.com/user-attachments/assets/e1876355-c68f-4b1a-8e0e-9bcbeaab6c98" />

You can also use this query:

```
select 

s.increment_id

from sales_order_status_history as sh

join  sales_order s on s.entity_id = sh.parent_id

where sh.comment = 'Etwas ist schiefgelaufen. Wählen Sie eine andere Zahlungsart für den Bezahlvorgang und versuchen Sie es erneut.'
AND s.created_at >= DATE_SUB(NOW(), INTERVAL 14 DAY)

order by sh.parent_id desc
limit 10

```

**Comment by dimadidr** [comment]
Hi @ijozwiak,

Thank you for reporting this issue and providing details.
We're currently investigating - it's a bit tricky to reproduce consistently on our side, but we're working on narrowing it down. We'll update this thread once we have more findings or a fix available.

Thank you,
Dima

**Comment by dimadidr** [comment]
Hi @ijozwiak,

Thank you for your patience.
Please find attached a patch for the issue. You can apply it using the following command:

`git apply ASD-1291.patch`

[ASD-1291.patch](https://github.com/user-attachments/files/23130734/ASD-1291.patch)


Thank you,
Dima

**Comment by ijozwiak** [comment]
Hello! Thank you very much for your support. The provided patch has partially resolved the issues; however, there is still one case that remains unresolved.

When `canceled` status is received `\Amazon\Pay\Model\AsyncManagement\Charge::processStateChange` is executed then the below code

```php
case 'Canceled':
    $this->setProcessing($order);
    $this->cancel($order, $charge['statusDetails']);
    $complete = true;
    break;
```

I do not understand why there is `$this->setProcessing($order);` called. It execute additional plugins in magento and it doesn't make sense from my perspective. If the order should be canceled why there is `processing` status and stage set?

**Comment by dimadidr** [comment]
Hi @ijozwiak,

Good catch - this was done to move the order out of the `payment_review` status into the usual order status flow, but as you pointed out, it’s not optimal.

I’ve prepared a patch that aligns the order cancellation logic with how Magento handles it natively and removes the extra `setProcessing` call.

Could you please apply the attached patch?

`git apply ASD-1291-cancel.patch`

[ASD-1291-cancel.patch](https://github.com/user-attachments/files/24458069/ASD-1291-cancel.patch)

Thank you,
Dima

**Comment by bolasevich** [comment]
I've got this patch installed however i just got a order and its still doing it.. order came in as authorize and then 30minutes later it canceled it and all it says in the comments is "Session canceled due to internal server error"

**Comment by bolasevich** [comment]
100% not working at all

Jan 19, 2026 4:38:00 PM Canceled Customer Not Notified
Something went wrong. Choose another payment method for checkout and try again.
Jan 19, 2026 3:41:02 PM Processing Customer Not Notified
Captured amount of $644.90 online. Transaction ID: "P01-xxxx-xxx-xxxx-capture"
Jan 19, 2026 3:40:47 PM Processing Customer Not Notified
Authorized amount of USD $644.90. Transaction ID: "xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxx"

**Comment by dimadidr** [comment]
Hi @bolasevich,

Could you please share the Magento and Amazon Pay logs related to this issue?
There might also be relevant exceptions in the logs connected to the message “Session canceled due to internal server error.”

Thank you,
Dima

**Comment by bolasevich** [comment]
FYI so far the fix has been to switch the payment mode from Immediate to Automatic and we aren't having any more issues.. in terms of logs when immediate mode was enabled i have the follow

orders in magento say

Jan 18, 2026 2:05:38 PM Processing Customer Not Notified
Captured amount of $475.45 online. Transaction ID: "-capture" (notice here there is no ID.. this is a problem)
Jan 18, 2026 1:30:36 PM Processing Customer Not Notified
Authorized amount of USD $475.45. Transaction ID: "xxx-xxxx-xxxx-8c44-7e5a8c63e84c"

and relevant logs

[2026-01-18T19:05:37.990052+00:00] amazonClientLogger.DEBUG: AmazonCleanUpIncompleteSesssions: Checkout session Open, completing: xxxxx-xxxxx-430d-8c44-7e5a8c63e84c [] []
[2026-01-18T19:05:38.424110+00:00] amazonClientLogger.DEBUG: completeCheckoutSession <-  ["1","xxxx-03e9-430d-8c44-xxxx","475.4500","USD"] []
[2026-01-18T19:05:38.424290+00:00] amazonClientLogger.ERROR: completeCheckoutSession ->  {"reasonCode":"InvalidCheckoutSessionStatus","message":"You tried to call an operation on a Checkout Session that is in a state where that operation is not allowed","status":422} []
[2026-01-18T19:05:38.787162+00:00] amazonClientLogger.DEBUG: captureCharge <-  ["1",null,"475.4500","USD"] []
[2026-01-18T19:05:38.787342+00:00] amazonClientLogger.ERROR: captureCharge ->  {"reasonCode":"MethodNotAllowed","message":"Http Method [POST] you are trying on resource [/live/v2/charges//capture] is not supported","status":405} []
[2026-01-18T19:05:39.152692+00:00] amazonClientLogger.DEBUG: getCharge <-  ["1",null] []
[2026-01-18T19:05:39.152891+00:00] amazonClientLogger.ERROR: getCharge ->  {"reasonCode":"MethodNotAllowed","message":"Http Method [GET] you are trying on resource [/live/v2/charges/] is not supported","status":405} []
[2026-01-18T19:10:04.149992+00:00] amazonClientLogger.DEBUG: AmazonCleanUpIncompleteSesssions: Cleaning up checkout

**Comment by dimonpvt1236** [comment]
any updates on this issues? It's still actual for me too

**Comment by dimadidr** [comment]
Hi @dimonpvt1236,

Could you please apply the attached patch?

[ASD-1291-order-cancel.patch](https://github.com/user-attachments/files/27966990/ASD-1291-order-cancel.patch)

The cancellation comes from a duplicate `completeCheckoutSession` call - the resulting exception is caught in the cleanup block, which then triggers `cancelOrder()`. Patch attached: idempotency guard on `charge_permission_id` at the top of `completeCheckoutSession()`, plus persisting that field at the top of `handlePayment()` so the guard also catches concurrent duplicates.

Please let me know if this helps. If the issue still happens after applying the patch, could you please provide the related logs?

Thank you,
Dima

**Comment by dimonpvt1236** [comment]
@dimadidr Thanks will try it.

But i install both prev patches from this issue, and found similar problem with cancel paid order:

We observed a production case where an Amazon Pay order was successfully completed and captured, but then got canceled in Magento after a later request to the Amazon Pay cancel callback URL (/amazon_pay/checkout/cancel/redirect/...).
**As a result:**

Magento order becomes canceled
Amazon charge remains Captured / paid
no refund is triggered
This creates an inconsistent state between Magento and Amazon Pay.

**Environment**
Magento: 2.4.7-p8
Amazon Pay module: 5.18.3 (from runtime log metadata)
Checkout flow: Amazon Pay (PayAndShip, payment intent Authorize + capture flow)
Production logs only (single log folder for this incident)
What we expected
If payment is already captured (or order is already finalized), cancel callback should not cancel the order in Magento, or should enforce a safe reconciliation flow.

What actually happened
A request to amazon_pay/checkout/cancel/redirect/... happened after successful completeCheckoutSession and capture, and Magento order was canceled, but no refund was created.

**Anonymized timeline (UTC)**
_Order A (canceled after capture)_
00:49:09 completeCheckoutSession -> status=200 with chargePermissionId + chargeId
00:49:10 async log: Captured Order #ORDER-A
00:49:11 updateChargePermission with merchantReferenceId=ORDER-A
00:51:52 access log: GET /amazon_pay/checkout/cancel/redirect/... (referrer: https://apay-us.amazon.com/)
00:51:52 async log: payment canceled email sent for ORDER-A
No refund-related log entries for ORDER-A

_Order B (same customer/cart amount, successful)_
New checkout started shortly after
completeCheckoutSession -> status=200
captureCharge -> Captured
Order remains successful (no cancel callback effect)

**Anonymized log excerpts**
```
[2026-05-12T00:49:09.377262+00:00] amazonClientLogger.DEBUG: completeCheckoutSession -> {"checkoutSessionId":"SESSION_A","status":200,"chargePermissionId":"CP_A","chargeId":"CH_A"} []
[2026-05-12T00:49:10.328674+00:00] amazonAsyncIpnLogger.INFO: Captured Order #ORDER-A [] []
[2026-05-12T00:49:11.180079+00:00] amazonClientLogger.DEBUG: updateChargePermission -> {"chargePermissionId":"CP_A","merchantMetadata":{"merchantReferenceId":"ORDER-A"},"status":200} []
[12/May/2026:00:51:52 +0000] "GET /amazon_pay/checkout/cancel/redirect/REDIRECT_TOKEN/ HTTP/1.1" 302 31 "https://apay-us.amazon.com/" ...
[2026-05-12T00:51:52.496792+00:00] amazonAsyncIpnLogger.INFO: Payment cancelled email sent for Order #ORDER-A [] []
[2026-05-12T00:54:11.596079+00:00] amazonClientLogger.DEBUG: completeCheckoutSession -> {"checkoutSessionId":"SESSION_B","status":200,"chargePermissionId":"CP_B","chargeId":"CH_B"} []
[2026-05-12T00:54:12.144612+00:00] amazonClientLogger.DEBUG: captureCharge -> {"chargeId":"CH_B","statusDetails":{"state":"Captured"},"status":200} []
[2026-05-12T00:54:12.553414+00:00] amazonAsyncIpnLogger.INFO: Captured Order #ORDER-B [] []
```

**Why this looks like a plugin issue**
Controller/Checkout/Cancel appears to call cancelOrder(...) for last Amazon order in session without checking if payment was already captured/finalized.
If cancel callback arrives late, it can cancel a paid order.

**Request**
Could maintainers confirm expected behavior for late checkoutCancelUrl callbacks and suggest/fix guard logic to prevent cancellation of already captured/finalized orders?

**Notes**
We do have local patches in production (including Amazon-related ones), but this late cancel callback behavior seems fundamentally unsafe and we want to align with upstream best practice.
