### ISSUE TITLE
Amazon Pay not showing up as payment method with Magento 2.3.1

### ISSUE THREAD

**Issue by ghost** [amzn/amazon-payments-magento-2-plugin#478]
#### Your setup

* Magento version: 2.x.x
* Amazon Pay Extension Version: 
* Magento Edition: Community / Enterprise / Enterprise Cloud
* JavaScript Console: Please add a screenshot of the Chrome JavaScript console to speed up the process
* Shop URL : 

Hello,

I have upgraded magento to 2.3.1 version and also updated the Amazon pay module as well to 3.1.4

But the Amazon Pay option is not showing on Payment method section on frontend even if we have configured the Payment method from admin panel properly with all credentials.

The Amazon pay method option in Payment method section was showing proper in Magento 2.3.0 but after upgrade to magento 2.3.1 it is not showing.

I have attached all the necessary screenshots. Kindly check this ASAP.

Thanks.
![Amazon Pay Payment method frontend](https://user-images.githubusercontent.com/30285726/56882545-8cf98900-6a81-11e9-925d-5de1237c5f2e.png)
![Amazon Pay Options frontend](https://user-images.githubusercontent.com/30285726/56882546-8cf98900-6a81-11e9-884d-f1d12fa64912.png)
![Amazon Pay Options](https://user-images.githubusercontent.com/30285726/56882547-8d921f80-6a81-11e9-9767-70501c8deb8e.png)
![Amazon Credentials Working](https://user-images.githubusercontent.com/30285726/56882548-8d921f80-6a81-11e9-8fcb-aa659b07112b.png)

**Comment by lemked** [comment]
Dear @NirmalRaval ,

Thanks for reporting this issue. I can confirm that this problem exists in Magento 2.3.1 / version 3.1.4 of our extension. We have already merged a bug fix into our code base (see #446 and #447) that will be available with the upcoming Magento 2.3.2 / 2.2.9 release.

Leaving open until released and confirmed.

Kind regards,
Daniel

**Comment by NirmalRaval** [comment]
Hello @lemked ,
Thank you for assist, but the solution which you have provided it is not working for us. We have upgraded amazon-pay-and-login-magento-2-module 3.1.5, and also applied above patch in it, still Amazon Pay payment method is not visible on checkout page.
We can see Amazon Pay option at minichart and shopping cart page (Please see attached screenshots), but it is not showing on checkout page (payment method options).
Can you please look into this issue? Please provide solution of this issue.
Thank you.
![amazon-pay-cart-minicart-page](https://user-images.githubusercontent.com/30285726/57604911-0796ce00-7583-11e9-80e3-5a820f32b5ac.png)
![amazon-pay-checkoutpage-](https://user-images.githubusercontent.com/30285726/57604912-0796ce00-7583-11e9-896d-ad375463619f.png)

**Comment by lemked** [comment]
Hi @NirmalRaval ,

I believe that's a different issue. Are you using any kind of extension that modified the checkout page? The one above looks like some kind of 3rd party OneStepCheckout extension.

Kind regards,
Daniel

**Comment by lemked** [comment]
@NirmalRaval , can you provide feedback on my last question? I'd like to close this issue as the general problem with Amazon Pay has been solved with our latest release (2.3.2). The problem you have encountered is probably related to some 3rd party extension instead.

**Comment by lemked** [comment]
Resolving as this is fixed with 2.3.2 and no further feedback provided here.

**Comment by amitpadwal** [comment]
> Hello @lemked ,
> Thank you for assist, but the solution which you have provided it is not working for us. We have upgraded amazon-pay-and-login-magento-2-module 3.1.5, and also applied above patch in it, still Amazon Pay payment method is not visible on checkout page.
> We can see Amazon Pay option at minichart and shopping cart page (Please see attached screenshots), but it is not showing on checkout page (payment method options).
> Can you please look into this issue? Please provide solution of this issue.
> Thank you.
> ![amazon-pay-cart-minicart-page](https://user-images.githubusercontent.com/30285726/57604911-0796ce00-7583-11e9-80e3-5a820f32b5ac.png)
> ![amazon-pay-checkoutpage-](https://user-images.githubusercontent.com/30285726/57604912-0796ce00-7583-11e9-896d-ad375463619f.png)

Hello Ghost...Did you find resolution to this...I have this same issue and at this point not looking to upgrade to Magento 2.3.2. Need a fix on Magento 2.3.1 and Amazon pay 3.1.4 version to appear Amazon pay in payment methods for standard checkout. Thanks...Amit

**Comment by lemked** [comment]
Hi @amitpadwal ,

The issue mentioned above was probably caused due to using a 3rd party extension that is modifying the checkout. Can you please create a new issue here on GitHub and provide details on which extensions you are using? We will look into it then.

Kind regards,
Daniel

**Comment by Puru2016** [comment]
I am using magento ver 2.3.5-p2 default setup and I am still facing the same issue.
Is there any solution or update on this.

**Comment by Puru2016** [comment]
Show Amazon Pay in payment methods option is also not working, I want to show Amazon payment method with other payment method on checkout.
Is there any solution for this issue?

**Comment by christianzichichi** [comment]
Hi @Puru2016 .
I would recommend to move to our new marketplace module, as the in-core module is not maintained anymore: 

https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html

https://amzn.github.io/amazon-payments-magento-2-plugin/installation.html

Thanks
Best

Christian

**Comment by Puru2016** [comment]
@christianzichichi  I am using magento2.3.1, should I upgrade the Amazon pay with latest version?

**Comment by christianzichichi** [comment]
Yes the plugin here https://marketplace.magento.com/amzn-amazon-pay-magento-2-module.html is compatible with Magento 2.3.1

@Puru2016 

Christian

**Comment by Puru2016** [comment]
@christianzichichi Thanks for reply.

I have upgraded the module and after configuration I will check "Show Amazon Pay in payment methods" option, but I think there is no further code available for "Show Amazon Pay in payment methods" option, please confirm 

Thanks

**Comment by christianzichichi** [comment]
Hi @Puru2016 , the payment method option is present in the new plugin. can be activated via the dedicated toggle: https://amzn.github.io/amazon-payments-magento-2-plugin/configuration.html#show-amazon-pay-method

Thanks
Best
Christian
