### ISSUE TITLE
Can not get Multi Currency to work with SEK or other BASE-currencies than EUR.

### ISSUE THREAD

**Issue by HansiBlomberg** [amzn/amazon-payments-magento-2-plugin#734]
#### What I expected

I expected the Amazon Payment method to work when I have SEK as my store base currency, because SEK is one of the supported Multi-Currency currencies and my Amazon account is in the EUR region.

#### What happened instead

Backend message:
An unsupported currency is currently selected. Please review our configuration guide.

Frontend: Module is not active, nothing from the module is displayed. Both the Amazon Pay and the Login with Amazon functionality is missing.

#### Steps to reproduce the issue

Install Magento 2.3.5-P1
Install the Amazon Payment module patches to update it to 3.5.1
Set the BASE currency in magento to SEK
Enter all credentials for the Amazon Payment module
Set Payment region to Euro Region
Save settings

#### Your setup

* Magento version: 2.3.5-P1
* Amazon Pay Extension Version: 3.5.1
* Magento Edition: Community

Note: If I change my store to EUR as base currency, Amazon Pay and Login will work. But I need the base currency set to SEK because that is what my other payment gateways expect.

**Comment by christianzichichi** [comment]
Hi @HansiBlomberg , 
thanks for contacting us. The Magento base currency needs to match exactly the "Payment region" parameter set in the module (EUR in your case) in order for the Amazon Pay button to show. Once Multicurrency option is enabled, SEK should be set as "Default Display Currency" and among the "Allowed Currencies".  Let us know if this solves your issue.

Thanks
Regards

Christian

**Comment by HansiBlomberg** [comment]
> 
> 
> Hi @HansiBlomberg ,
> thanks for contacting us. The Magento base currency needs to match exactly the "Payment region" parameter set in the module (EUR in your case) in order for the Amazon Pay button to show. Once Multicurrency option is enabled, SEK should be set as "Default Display Currency" and among the "Allowed Currencies". Let us know if this solves your issue.
> 

No, it does not solve MY issue.
That is a design flaw that make it impossible for me to use Amazon Pay.

The Magento BASE currency is the currency that Magento will use at checkout, regardless of the DISPLAY currency.

The majority of my customers are from Sweden
Therefore, the charges on customers credit cards when they check ut with PAYPAL or other payment gateways need to be in SEK.

Therefore - changing the BASE currency to anything else than SEK can not be done.

Any shop based in EU country that is NOT using EUR will have the same issue. Example:
Bulgaria, Croatia, Czech Republic, Denmark, Hungary, Poland, Romania

**Comment by christianzichichi** [comment]
Hi @HansiBlomberg ,
thanks for your feedback. We'll look into the issue with priority and report back here.

Thanks
Regards

Christian

**Comment by christianzichichi** [comment]
Hi @HansiBlomberg ,
Sorry for the inconvenience. We have just released new patchsets that bring Amazon Pay version to 3.6.1: 
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/PATCH_INSTRUCTIONS.MD

The new version contains a bugfix for the multicurrency issue described here. Please let us know if this solves or if you have any other issues with the extension.

Thanks
Regards

Christian

**Comment by HansiBlomberg** [comment]
> 
> 
> Hi @HansiBlomberg ,
> I apologize for the inconvenience. We have just released new patchsets that bring Amazon Pay version to 3.6.1:
> https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/PATCH_INSTRUCTIONS.MD
> 
> The new version contains a bugfix for the multicurrency issue described here. Please let us know if this solves or if you have any other issues with the extension.
> 
> Thanks
> Regards
> 
> Christian

There is no change in behaviour.

**Comment by christianzichichi** [comment]
Hi @HansiBlomberg ,
is multi-currency option enabled under Advanced->Sales Options ? 
In 3.6.1, we removed base currency and payment region match constraint. Payment region must now match display currency, and this constraint is removed if multi-currency option is enabled, hence you should be able to see the Amazon Pay button and transact in SEK.
Please contact us at payments-cp-devel@amazon.com. We will ask you more information about your specific environments/settings that will allow us to dive deep into the issue and find the cause.

Thanks
Regards

Christian

**Comment by HansiBlomberg** [comment]
> 
> 
> Hi @HansiBlomberg ,
> is multi-currency option enabled under Advanced->Sales Options ?
> In 3.6.1, we removed base currency and payment region match constraint. Payment region must now match display currency, and this constraint is removed if multi-currency option is enabled, hence you should be able to see the Amazon Pay button and transact in SEK.
> Please contact us at [payments-cp-devel@amazon.com](mailto:payments-cp-devel@amazon.com). We will ask you more information about your specific environments/settings that will allow us to dive deep into the issue and find the cause.
> 
> Thanks
> Regards
> 
> Christian

Actually, I was to quick on the trigger. It is just that the backend is still showing the error message

An unsupported currency is currently selected. Please review our configuration guide
Front end IS working now, so i say thank you very very much!

I will spend some time testing, will let you know if I find anything that is not working as expected.

**Comment by christianzichichi** [comment]
@HansiBlomberg ,
thanks a lot for the feedback. In the meantime,  we will look into the reported backend error message and remove it 

Thanks
Regards

Christian

**Comment by christianzichichi** [comment]
Hi @HansiBlomberg ,
I'm going to close this as the issues described were solved. Please feel free to reopen or contact us at payments-cp-devel@amazon.com if you have any other issue with the extension.

Thanks
Regards

Christian
